# Generated by Django 3.2.9 on 2021-11-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.FileField(default='download.jpg', upload_to='./pics'),
        ),
    ]
