# Generated by Django 3.2.8 on 2021-11-16 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_auto_20211116_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmovie',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 13, 25, 50, 707161, tzinfo=utc)),
        ),
    ]
