# Generated by Django 3.2.8 on 2021-11-17 13:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_auto_20211116_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmoviemodel',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 13, 59, 15, 60692, tzinfo=utc)),
        ),
    ]
