# Generated by Django 3.2.8 on 2021-11-17 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0019_auto_20211117_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmoviemodel',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 19, 24, 12, 333465, tzinfo=utc)),
        ),
    ]
