# Generated by Django 3.2.8 on 2021-12-06 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0029_alter_commentmoviemodel_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmoviemodel',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 17, 20, 12, 219562, tzinfo=utc)),
        ),
    ]
