# Generated by Django 3.2.8 on 2021-12-06 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0033_alter_commentmoviemodel_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmoviemodel',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 19, 8, 50, 295355, tzinfo=utc)),
        ),
    ]
