# Generated by Django 3.2.8 on 2021-11-02 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20211101_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 16, 52, 8, 176644, tzinfo=utc)),
        ),
    ]
