# Generated by Django 3.2.8 on 2021-12-06 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0059_auto_20211117_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 17, 20, 12, 225694, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 17, 20, 12, 223635, tzinfo=utc)),
        ),
    ]
