# Generated by Django 3.2.8 on 2021-12-06 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0060_auto_20211206_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 19, 4, 27, 472588, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 19, 4, 27, 471406, tzinfo=utc)),
        ),
    ]
