# Generated by Django 3.2.8 on 2021-12-06 19:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0064_auto_20211206_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 19, 9, 32, 894971, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 19, 9, 32, 893844, tzinfo=utc)),
        ),
    ]
